version: '3.8'

services:
  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
  
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
