services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  
      - sqlite_data:/app  
    env_file:
      - .env.example  
    restart: always  

volumes:
  sqlite_data:  
